### ISSUE TITLE
2.0.8 fails to build

### ISSUE THREAD

**Issue by W-Floyd** [linuxdeepin/dtkwidget#10]
Building under Solus, all dependencies updated. `2.0.7.3` still builds, but `2.0.8` fails with:
```
Project ERROR: The format of the value of TARGET is incorrect. eg: dtk[a-z0-9]+
```

**Comment by W-Floyd** [comment]
Seems the 2.0.8 tag changed early on, and I had the old version. `git fetch --tags` fixed it, and it's building now.

**Comment by W-Floyd** [comment]
Now I'm stuck with
```
/home/build/YPKG/root/dtkwidget/build/dtkwidget.git/build/tools/svgc/../../src//libdtkwidget.so: undefined reference to `XISelectEvents'
/home/build/YPKG/root/dtkwidget/build/dtkwidget.git/build/tools/svgc/../../src//libdtkwidget.so: undefined reference to `XIQueryVersion'
/home/build/YPKG/root/dtkwidget/build/dtkwidget.git/build/tools/svgc/../../src//libdtkwidget.so: undefined reference to `XGetExtensionVersion'
```
Which seems... weird.

**Comment by Johnnynator** [comment]
Seems like it is already fixed in master. 
https://github.com/linuxdeepin/dtkwidget/commit/ee8a64190b62a083e1c10c4949ca1e296befbfd3

**Comment by W-Floyd** [comment]
Thanks! I really should have looked first...
