### ISSUE TITLE
交叉编译时安装文件的路径不正确

### ISSUE THREAD

**Issue by Yanhao** [linuxdeepin/dtkwidget#15]
和这个问题一样的

https://github.com/linuxdeepin/dtkcore/issues/10

**Comment by Iceyer** [comment]
dtkwidget好像用的是dtkcore的prf文件，你试试先更安装下dtkcore到最新版本

**Comment by BLumia** [comment]
这个问题现在是已经处理过了吧？

**Comment by Iceyer** [comment]
恩，没问题先关掉了
