### ISSUE TITLE
Updated to latest 2.0.9.17-2.2 in Manjaro (Arch) and the dock reloaded multiple times

### ISSUE THREAD

**Issue by hkirsman** [linuxdeepin/dtkwidget#18]
I guess this is the update in Arch https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/dtkwidget&id=3ef6349fee3ab0518b9a16a5bae8ee0f9281e7cd

Any thoughts why it happened? Will keep updated if it continues.

**Comment by hkirsman** [comment]
It continued, used downgrade command to downgrade to dtkwidget-2.0.9.17-1-x86_64.pkg.tar.xz

**Comment by BLumia** [comment]
Cannot reproduce this issue under Arch (Manjaro is not Arch, btw)

Probably related: https://github.com/linuxdeepin/developer-center/issues/1023#issuecomment-476506295

**Comment by hkirsman** [comment]
Installed yesterday dtkwidget  2.0.9.17-2.6 and the problem has not reoccured.
