### ISSUE TITLE
error: dtkwidget development package not found

### ISSUE THREAD

**Issue by xiedonghuilove** [linuxdeepin/dtkwidget#2]
Hello, my operating system is window, I recently compiled a project, you need to use dtkwidget.
I would like to ask, how to install the window under the dtkwidget library.
thank you

**Comment by Iceyer** [comment]
if you want to build application base on dtk, you can just build dtk static on windows. or can get precompile file from https://ci.deepin.io/view/apps%20on%20windows/

Or you can build by this script on window，replace vs path and qt path on yourself system.
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
SET QTPATH=D:\Develop\Qt\Static\5.8.1\vs2017
SET QMAKE=%QTPATH%\bin\qmake.exe
SET PATH=%QTPATH%\bin;%PATH%

mkdir build
cd build
set INCLUDE_INSTALL_DIR=D:\Develop\LibraryCI\include
set LIB_INSTALL_DIR=D:\Develop\LibraryCI\lib
set _CL_=/utf-8
set CL=/MP

%QMAKE% -r CONFIG+=release "VERSION=%GIT_VERSION%" "LIB_INSTALL_DIR=D:\Develop\LibraryCI\lib" "INCLUDE_INSTALL_DIR=D:\Develop\LibraryCI\include"  ..

nmake.exe clean
nmake.exe
nmake.exe install
cd ..
```
