### ISSUE TITLE
qmake version in readme

### ISSUE THREAD

**Issue by gaoyaoxin** [linuxdeepin/dtkwidget#3]
```
qmake --version
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu
```
I found that the qmake version on my computer which successfully installed this package is 3.0, so should the qmake version line (line 9) in readme be modified into possibly Qt version?

**Comment by Iceyer** [comment]
Yes，Is mean the qt version，not qmake version.
And we will update the support version of qt to 5.6 as soon as possible.
