### ISSUE TITLE
问下大佬们dtk

### ISSUE THREAD

**Issue by xiaoc-arch** [linuxdeepin/dtkwidget#31]
deepin的主题现在是统一了gtk应用吗？像深度编辑器，系统监视器，文管，深度终端是基于dtk开发的吗？deepin主题是dtk主题吗？dtk主题支持qt gtk dtk 应用主题大一统吗？主题美化（圆角像素太大？窗口边线不透明？归档管理器和文档查看器下边是直角？标题栏高度？）这些该如何下手？deepin-gtk-theme对dtk应用不起作用啊？有没有dtk应用主题的统一入口？

**Comment by BLumia** [comment]
> deepin的主题现在是统一了gtk应用吗？

并非统一。Deepin 有提供 GTK 主题和 Qt 主题，所以 GTK 和 Qt 应用程序会长得比较像 DTK 的风格，但并非意义上的统一。

> 像深度编辑器，系统监视器，文管，深度终端是基于dtk开发的吗？

你提到的这些，除了深度终端是 GTK/Vala 应用程序外，别的都是 DTK 应用程序。

> 归档管理器和文档查看器下边是直角？

归档管理器和文档查看器不是 Deepin 的应用，是 GTK 的。

> deepin-gtk-theme对dtk应用不起作用啊？

DTK 和 GTK 没什么关系，所以改 GTK 主题肯定影响不到 DTK 应用。目前除深度终端外的所有应用都是 DTK 的。

> 有没有dtk应用主题的统一入口？

目前是没有的，以后可能会有但大概也不会有很高的可定制性，不过可以去 [开发者中心](https://github.com/linuxdeepin/developer-center/issues) 请求相关的特性，以便产品和设计那边考虑。

--------------

更多问题的话请发到 [开发者中心](https://github.com/linuxdeepin/developer-center/issues) ，这个 Issue 就先关掉了。
