### ISSUE TITLE
添加多选列表控件

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/dtkwidget#332]
1. 目前的DListView的列表控件并不满足我需要的可多选，搜索以及点击事件的需求。
2. 该控件包括三部分，操作栏（包括搜索以及一些按钮），表头，以及列表内容，列表可多选。
期望效果
![图片](https://user-images.githubusercontent.com/52627687/220016082-5ac806c5-6f60-4625-bd1f-5def7c7094df.png)

**Comment by zccrs** [comment]
具体是哪项功能做不到呀？“多选”这个动作本身 listview 是支持的。

**Comment by zccrs** [comment]
期望的效果只有一个图，是UI层面什么东西做不到，还是行为层面？

**Comment by chenchongbiao** [comment]
https://user-images.githubusercontent.com/52627687/220343295-99dea708-5518-42c5-a699-279487d99c7b.mp4

这里用的是QListWidget做的数据展示，不止是展示文本数据，像右边我希望选中的数据能够显示有CheckBox控件的显示，以及表头那里会有个代表全部选中的CheckBox，就是否会考虑封装一下QListWidget。

**Comment by chenchongbiao** [comment]
![图片](https://user-images.githubusercontent.com/52627687/220345392-dd98a55b-dfdd-449c-824d-7f71fccebcca.png)
我在dtkwidget的那个example那里DComboBox有一张截图应该是专业版的软件，下面那部分应该QListWidget做的，那块地方的列表是我期望的效果，如果觉得可以的话，可以把上面的搜索框以及按钮等操作的部分也作为一个整体，像这个列表展示以及搜索的东西，在Web的前端是比较常见的，不知道在桌面应用这里，这部分的功能是否有需求，封装一个列表控件。

**Comment by zccrs** [comment]
> 

这种效果用QListView应该是比较容易实现的，dtkwidget现在不打算再封装新的控件了，准备大力发展 dtkdeclarative。如果能实现这个效果，只是程序开发中需要多写代码，那最好是程序中来实现。如果是其他情况，必须要dtkwidget修改才能做到，那可以考虑修改dtkwidget。

**Comment by chenchongbiao** [comment]
好的 明白了
