### ISSUE TITLE
窗口左上角应用图标出现锯齿状

### ISSUE THREAD

**Issue by iCancely** [linuxdeepin/dtkwidget#347]
【环境】
仓库地址：
deb http://pools.uniontech.com/desktop-professional eagle main contrib non-free
deb http://pools.uniontech.com/ppa/dde-eagle eagle/1060 main contrib non-free

libdtkgui5 5.6.8
libdtkwidget5 5.6.8
dde-qt5integration 5.6.5

【前置条件】
电脑分辨率：2560x1600
缩放：1.5倍

【问题】
所有应用左上角的应用图标出现明显锯齿，希望没有锯齿，平滑显示。

<img width="733" alt="image" src="https://user-images.githubusercontent.com/111953898/223028483-f5465214-852c-4979-bb20-06aeb2599bfb.png">

**Comment by zccrs** [comment]
PR合入前要通过 @iCancely 的确认。

**Comment by kegechen** [comment]
[xdgiconloader.zip](https://github.com/linuxdeepin/dtkwidget/files/10954183/xdgiconloader.zip)

xdgiconloader 获取 pixmap 时较不同的方式（实际是Qt又乘以了一次缩放导致图片更大导致）

![image](https://user-images.githubusercontent.com/23466548/224625332-160ede77-8a85-4d65-8eb7-59009eb7fc35.png)

图1是缩放模糊的效果
图2是家加上 patch 重新编译的 libqtxdg 之后的效果

**Comment by zccrs** [comment]
> 

正好可以试一下新加的 KIconLoader https://github.com/linuxdeepin/dtkgui/pull/135

**Comment by kegechen** [comment]
> > 
> 
> 正好可以试一下新加的 KIconLoader [linuxdeepin/dtkgui#135](https://github.com/linuxdeepin/dtkgui/pull/135)

这个可以有

**Comment by kegechen** [comment]
https://github.com/linuxdeepin/qt5integration/issues/128 一样的问题。
关闭 插件中的issue,保留这一个

**Comment by BLumia** [comment]
> 但是无法跟随xdg图标主题

https://github.com/linuxdeepin/dtkgui/pull/135 的这个使用 KIconEngine 时无法切主题的问题，目前判断是 KIconLoader 使用的 KIconTheme 的问题，具体还没细看，需要随后仔细看下。在解决这个问题之前，我会把对应的 PR 转成 draft 状态。

**Comment by kegechen** [comment]
v23 不存在此问题。 因为v23上qtxdg版本是3.6已经包含了patch的部分

**Comment by kegechen** [comment]
v23不存在此问题。只在专业版有。专业版可以加上此patch。
