### ISSUE TITLE
支持通过 DConfig 配置 DTitleBar 的默认高度

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/dtkwidget#367]
嫌弃deepin自研程序大额头的声音一直没有中断过，虽然是否需要修改默认的标题栏高度这件事存疑，不过我们可以提供 DConfig 允许对它深恶痛绝的人来修改它。

**Comment by chenchongbiao** [comment]
尝试解决该问题

信息记录：
deepin-tweak 中支持设置第三方的标题栏修改
Server-side decoration 的标题是由窗管绘制

**Comment by chenchongbiao** [comment]
我看了下DTitlebar的源码，如果我想设置应用的标题栏的默认大小，那我使用DConfig，创建一个配置，里面配置上标题栏高度的配置项，在初始化该控件时读取该配置文件设置默认的大小
这样理解对不？

**Comment by zccrs** [comment]
> 我看了下DTitlebar的源码，如果我想设置应用的标题栏的默认大小，那我使用DConfig，创建一个配置，里面配置上标题栏高度的配置项，在初始化该控件时读取该配置文件设置默认的大小 这样理解对不？

赞，就是这个意思

**Comment by chenchongbiao** [comment]
那现在有2个问题

1.我需要创建一个新的配置文件不，还是从已有的配置文件中有可加关于标题栏高度的。
2.这修改标题栏高度以什么形式提供给用户，还是说直接修改配置文件的value来修改标题栏的默认高度。

**Comment by chenchongbiao** [comment]
https://github.com/linuxdeepin/dtkwidget/pull/383

**Comment by kegechen** [comment]
https://github.com/linuxdeepin/dtkgui/pull/139 

https://github.com/linuxdeepin/dtkwidget/pull/383
https://github.com/linuxdeepin/dtkwidget/pull/387
