### ISSUE TITLE
/usr/lib/dtk2/dtk-svgc 的问题

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/dtkwidget#4]
你好，我是 Debian 中 `dtkwidget` 软件包的维护者。软件包信息可见于 https://tracker.debian.org/pkg/dtkwidget .

先前曾经反映过 `libdtkwidget-dev` 包夹带了 `/usr/lib/dtk2/dtk-svgc` 这个可执行文件的问题。该文件的存在会破坏 libdtkwidget-dev 的 Multi-Arch 状态，使之无法被标记为 `Multi-Arch: same` 而削弱了其交叉编译的能力。除此之外，dtk-svgc 实在和 dtkwidget 库没有什么联系。

因此，希望能重新评估一下 /usr/lib/dtk2/dtk-svgc 该二进制文件的存放位置；也许可以分割出一个 `libdtkwidget-bin` 包予以存放。

**Comment by Iceyer** [comment]
这个去年底已经做了规划，不过一直没有时间处理。我们尽量这两周处理玩。新的包会放在这里仓库：
https://github.com/linuxdeepin/dtktools

**Comment by Iceyer** [comment]
已经拆分出libdtkwidget-bin
