### ISSUE TITLE
非DDE安装dtk三件套和dqt dframeworkdbus 后DAboutDialog唤出段错误

### ISSUE THREAD

**Issue by SuperEndermanSM** [linuxdeepin/dtkwidget#64]
https://gitee.com/deepin-community-store/spark-dtk/releases
这些是已经安装的依赖
测试环境：ubuntu gnome 20.04

**Comment by xmuli** [comment]
对于多桌面混用产生的一些兼容性问题, 由于一些计划的倾向, 此方向可能目前暂无支持计划.
