### ISSUE TITLE
dtkwidget tag 版本和 debian/changelog不一致，请更新。

### ISSUE THREAD

**Issue by zhangn1985** [linuxdeepin/dtkwidget#65]

**Comment by xmuli** [comment]
嗯， 之前没有专人维护； 刚已经说一下

**Comment by zhangn1985** [comment]
很奇怪哈，你们https://community-packages.deepin.com/deepin/ 发布的源码包都有对应一致的debian/changelog，为啥不顺道上传？

**Comment by xmuli** [comment]
开发 和 集成发布不是同一波人

**Comment by zhangn1985** [comment]
汗，你们一家公司，就算加上统信，人也不多，大家协调一下，很容易呀。而且他们debian/compact都设置成9，导致大量软件都按照`-j1`来编译，速度巨慢，至少要设置成10才好。

**Comment by xmuli** [comment]
什么叫说起来容易，请带领我们做它。完善它。可以帮助更加完善，若是有兴趣，可以帮助内推，来教 Deepin 如何做软件（非杠）。
