### ISSUE TITLE
新版本dtk主题文件调整到哪里去了

### ISSUE THREAD

**Issue by yuxue521** [linuxdeepin/dtkwidget#66]
2.1.1 版本 的 dui_theme_light.qrc 现在调整到哪里去了，之前的版本读取样式 是从这里读取现在没有了

**Comment by kegechen** [comment]
您好， 新旧版本差异非常大并不兼容也不是一个包。旧的文件找不到很正常， 而且dtk5也不建议使用样式表来控制了样式了。
