### ISSUE TITLE
build

### ISSUE THREAD

**Issue by cancer-chain** [linuxdeepin/dtkwidget#67]
make
cd src/ && ( test -e Makefile || /usr/bin/qmake-qt5 -o Makefile /home/xxxxdb/下载/dtkwidget-master/src/src.pro ) && make -f Makefile 
make[1]: Entering directory '/home/xxxxdb/下载/dtkwidget-master/build/src'
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DENABLE_AI -DDTK_NO_MULTIMEDIA -DSN_API_NOT_YET_FROZEN -DQT_MESSAGELOGCONTEXT -DLIBDTKWIDGET_LIBRARY -DDTK_LIB_DIR_NAME=\"libdtk-2.0.6\" -DDWIDGET_TRANSLATIONS_PATH=\"/usr/share/libdtk-2.0.6/DWidget/translations\" -DDWIDGET_TRANSLATIONS_DIR=\"libdtk-2.0.6/DWidget/translations\" -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../src -I. -I../../src/util -I../../src/widgets/private/keyboardmonitor -I../../src/widgets/private/startupnotifications -I../../src/widgets -I/usr/include/qt5/QGSettings -I/usr/include/startup-notification-1.0 -I/usr/include/libdtk-2.0.6/DGui -I/usr/include/qt5/QtPrintSupport/5.15.1 -I/usr/include/qt5/QtPrintSupport/5.15.1/QtPrintSupport -I/usr/include/qt5/QtWidgets/5.15.1 -I/usr/include/qt5/QtWidgets/5.15.1/QtWidgets -I/usr/include/qt5/QtGui/5.15.1 -I/usr/include/qt5/QtGui/5.15.1/QtGui -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtX11Extras -I/usr/include/qt5/QtGui -I/usr/include/libdtk-2.0.6/DCore -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtConcurrent -I/usr/include/qt5/QtCore/5.15.1 -I/usr/include/qt5/QtCore/5.15.1/QtCore -I/usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o dapplicationsettings.o ../../src/util/dapplicationsettings.cpp
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DENABLE_AI -DDTK_NO_MULTIMEDIA -DSN_API_NOT_YET_FROZEN -DQT_MESSAGELOGCONTEXT -DLIBDTKWIDGET_LIBRARY -DDTK_LIB_DIR_NAME=\"libdtk-2.0.6\" -DDWIDGET_TRANSLATIONS_PATH=\"/usr/share/libdtk-2.0.6/DWidget/translations\" -DDWIDGET_TRANSLATIONS_DIR=\"libdtk-2.0.6/DWidget/translations\" -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../src -I. -I../../src/util -I../../src/widgets/private/keyboardmonitor -I../../src/widgets/private/startupnotifications -I../../src/widgets -I/usr/include/qt5/QGSettings -I/usr/include/startup-notification-1.0 -I/usr/include/libdtk-2.0.6/DGui -I/usr/include/qt5/QtPrintSupport/5.15.1 -I/usr/include/qt5/QtPrintSupport/5.15.1/QtPrintSupport -I/usr/include/qt5/QtWidgets/5.15.1 -I/usr/include/qt5/QtWidgets/5.15.1/QtWidgets -I/usr/include/qt5/QtGui/5.15.1 -I/usr/include/qt5/QtGui/5.15.1/QtGui -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtX11Extras -I/usr/include/qt5/QtGui -I/usr/include/libdtk-2.0.6/DCore -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtConcurrent -I/usr/include/qt5/QtCore/5.15.1 -I/usr/include/qt5/QtCore/5.15.1/QtCore -I/usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o daboutdialog.o ../../src/widgets/daboutdialog.cpp
../../src/widgets/daboutdialog.cpp: In member function ‘void Dtk::Widget::DAboutDialogPrivate::loadDistributionInfo()’:
../../src/widgets/daboutdialog.cpp:176:26: error: ‘distributionOrgLogo’ is not a member of ‘Dtk::Core::DSysInfo’
  176 |     logoPath = DSysInfo::distributionOrgLogo(DSysInfo::Distribution, DSysInfo::Light, ":/assets/images/deepin-logo.svg");
      |                          ^~~~~~~~~~~~~~~~~~~
../../src/widgets/daboutdialog.cpp:176:56: error: ‘Distribution’ is not a member of ‘Dtk::Core::DSysInfo’
  176 |     logoPath = DSysInfo::distributionOrgLogo(DSysInfo::Distribution, DSysInfo::Light, ":/assets/images/deepin-logo.svg");
      |                                                        ^~~~~~~~~~~~
../../src/widgets/daboutdialog.cpp:176:80: error: ‘Light’ is not a member of ‘Dtk::Core::DSysInfo’
  176 |     logoPath = DSysInfo::distributionOrgLogo(DSysInfo::Distribution, DSysInfo::Light, ":/assets/images/deepin-logo.svg");
      |                                                                                ^~~~~
../../src/widgets/daboutdialog.cpp:177:34: error: ‘distributionOrgWebsite’ is not a member of ‘Dtk::Core::DSysInfo’
  177 |     auto websiteInfo = DSysInfo::distributionOrgWebsite(DSysInfo::Distribution); // will always return a valid result.
      |                                  ^~~~~~~~~~~~~~~~~~~~~~
../../src/widgets/daboutdialog.cpp:177:67: error: ‘Distribution’ is not a member of ‘Dtk::Core::DSysInfo’
  177 |     auto websiteInfo = DSysInfo::distributionOrgWebsite(DSysInfo::Distribution); // will always return a valid result.
      |                                                                   ^~~~~~~~~~~~
../../src/widgets/daboutdialog.cpp: In member function ‘const QPixmap* Dtk::Widget::DAboutDialog::companyLogo() const’:
../../src/widgets/daboutdialog.cpp:338:40: warning: ‘const QPixmap* QLabel::pixmap() const’ is deprecated: Use the other overload which returns QPixmap by-value [-Wdeprecated-declarations]
  338 |     return d->companyLogoLabel->pixmap();
      |                                        ^
In file included from /usr/include/qt5/QtWidgets/QLabel:1,
                 from ../../src/widgets/daboutdialog.cpp:28:
/usr/include/qt5/QtWidgets/qlabel.h:78:20: note: declared here
   78 |     const QPixmap *pixmap() const; // ### Qt 7: Remove function
      |                    ^~~~~~
In file included from /usr/include/qt5/QtGui/qtguiglobal.h:43,
                 from /usr/include/qt5/QtGui/qicon.h:43,
                 from /usr/include/qt5/QtGui/QIcon:1,
                 from ../../src/widgets/ddialog.h:21,
                 from ../../src/widgets/daboutdialog.h:21,
                 from ../../src/widgets/daboutdialog.cpp:18:
../../src/widgets/daboutdialog.cpp: In member function ‘void Dtk::Widget::DAboutDialog::setAcknowledgementVisible(bool)’:
/usr/include/qt5/QtCore/qglobal.h:1158:43: warning: unused variable ‘d’ [-Wunused-variable]
 1158 | #define Q_D(Class) Class##Private * const d = d_func()
      |                                           ^
/usr/include/libdtk-2.0.6/DCore/dobject.h:29:20: note: in expansion of macro ‘Q_D’
   29 | #define D_D(Class) Q_D(Class)
      |                    ^~~
../../src/widgets/daboutdialog.cpp:532:5: note: in expansion of macro ‘D_D’
  532 |     D_D(DAboutDialog);
      |     ^~~
make[1]: *** [Makefile:2379: daboutdialog.o] Error 1
make[1]: Leaving directory '/home/xxxxdb/下载/dtkwidget-master/build/src'
make: *** [Makefile:49: sub-src-make_first-ordered] Error 2

**Comment by cancer-chain** [comment]
build  dtkwidget （qt-5.15）

**Comment by N1coc4colA** [comment]
> ../../src/widgets/daboutdialog.cpp
> ../../src/widgets/daboutdialog.cpp: In member function ‘void Dtk::Widget::DAboutDialogPrivate::loadDistributionInfo()’:
> ../../src/widgets/daboutdialog.cpp:176:26: error: ‘distributionOrgLogo’ is not a member of ‘Dtk::Core::DSysInfo’
> 176 | logoPath = DSysInfo::distributionOrgLogo(DSysInfo::Distribution, DSysInfo::Light, ":/assets/images/deepin-logo.svg");

DSysInfo (part of Dtkcore) have been introduced in version 2.0.9.5. Your bug means that you used an icompatible version of dtkcore with the dtkwidget version you're trying to compile. As DSysInfo::distributionOrgLogo appeared in dtkwidget version 5.0.9, I guess you're trying to compile at least a version of dtkwidget <5.0.9, just get a newer version and try again, that'll work

**Comment by dariusity** [comment]
Hi, I'm having issue building as well. The error was related to:
'dtkcore5.5'
'dtkgui5.5'
As both the '5.5' were not supposed to be there, it caused the build to fail, and I found that out because I checked with the prebuilt package provided by Arch.
If there's a fix please kindly hmu.

**Comment by dariusity** [comment]
Wow

**Comment by BLumia** [comment]
Sorry for the late reply. Since it's a pretty old issue, I'll close it for now.

We are using the [developer-center](https://github.com/linuxdeepin/developer-center/) repo to track issues and answer questions in discussion board, so if you still need help about building DTK, please feel free to ask us at [developer-center](https://github.com/linuxdeepin/developer-center/). Thanks!
