### ISSUE TITLE
DLineEdit::setFocus无法设置焦点

### ISSUE THREAD

**Issue by RigoLigoRLC** [linuxdeepin/dtkwidget#68]
![图片](https://user-images.githubusercontent.com/49363666/102121112-65d21400-3e7e-11eb-9074-0d60fb2b1e40.png)

`DDialog::focusWidget`可获得被我设置焦点的对象，但是该`DLineEdit`在DDialog中没有默认焦点。

**Comment by kegechen** [comment]
DDialog::focusWidget 能获取到焦点对象是 DLineEdit, 但是DLineEdit没有将焦点proxy给包含的QlineEdit, 可以算是一个小问题。 此处如果是想弹出的对话框可以直接再edit中输入文字可以尝试将 edit->setFocus(Qt::MouseFocusReason); 改成 edit->lineEdit()->setFocus(Qt::MouseFocusReason);

**Comment by RigoLigoRLC** [comment]
> DDialog::focusWidget 能获取到焦点对象是 DLineEdit, 但是DLineEdit没有将焦点proxy给包含的QlineEdit, 可以算是一个小问题。 此处如果是想弹出的对话框可以直接再edit中输入文字可以尝试将 edit->setFocus(Qt::MouseFocusReason); 改成 edit->lineEdit()->setFocus(Qt::MouseFocusReason);

确实是这个问题。已经修改issue标题等候下一步修复。

**Comment by RigoLigoRLC** [comment]
> DDialog::focusWidget 能获取到焦点对象是 DLineEdit, 但是DLineEdit没有将焦点proxy给包含的QlineEdit, 可以算是一个小问题。 此处如果是想弹出的对话框可以直接再edit中输入文字可以尝试将 edit->setFocus(Qt::MouseFocusReason); 改成 edit->lineEdit()->setFocus(Qt::MouseFocusReason);

7cebaec9d62b0c7585e8873bb59a0c14508f6321修复了这个问题；关闭issue。
