### ISSUE TITLE
头文件不规范

### ISSUE THREAD

**Issue by chen244** [linuxdeepin/dtkwidget#71]
![截图_选择区域_20210409163646](https://user-images.githubusercontent.com/60290287/114155881-8e61aa80-9954-11eb-857e-1aabd14e0c7e.png)

**Comment by kegechen** [comment]
收到。 会及时改正。 谢谢。

**Comment by chen244** [comment]
![截图_选择区域_20210411153020](https://user-images.githubusercontent.com/60290287/114296080-cba47480-9adb-11eb-8cb4-758173892ba0.png)
![截图_选择区域_20210411153123](https://user-images.githubusercontent.com/60290287/114296082-ccd5a180-9adb-11eb-902c-d8193f01a7e5.png)
![截图_选择区域_20210411153259](https://user-images.githubusercontent.com/60290287/114296084-cd6e3800-9adb-11eb-86f9-dbf7b80bc266.png)

**Comment by chen244** [comment]
追加，titlebar里面有一个没写virtual 两个没有写override造成编译器报警

**Comment by kegechen** [comment]
> 追加，titlebar里面有一个没写virtual 两个没有写override造成编译器报警

收到。
