### ISSUE TITLE
样式的一些问题

### ISSUE THREAD

**Issue by chen244** [linuxdeepin/dtkwidget#72]
![截图_选择区域_20210409212642](https://user-images.githubusercontent.com/60290287/114187275-62592000-997a-11eb-9584-e2969ae7699d.png)
这是设置了fixsize以后的窗口，最大化这个图标能默认去掉吗？你们的启动盘制作工具都可以没有，就不能默认没有吗？
![截图_选择区域_20210409212921](https://user-images.githubusercontent.com/60290287/114187526-aea46000-997a-11eb-8fcd-cb069ae5023b.png)
这是使用了你们样式的virturlbox。。。这个太离谱了吧

还有万年的spinbox。。。我都不想吐槽了。。。
![录屏_选择区域_20210409213152](https://user-images.githubusercontent.com/60290287/114187854-0ba01600-997b-11eb-96db-289bfc69fa7c.gif)
我并不认为这个menu选中的特效很好看

**Comment by kegechen** [comment]
1. 最大最小化这些按钮和windowFlags相关，setfixedsize只是禁止， 可以通过setWindowFlags的方法隐藏，如下
`setWindowFlags(windowFlags() & ~(Qt::WindowMinimizeButtonHint | 
Qt::WindowMaximizeButtonHint |
 Qt::WindowCloseButtonHint));` 
 
 2. 这个样式阔以通过命令行参数禁用，如`VirtualBox --style fusion` 这样应该阔以解决你的烦恼。。

 3.  万年的spinbox问题是否指的是spinbox中的edit太窄了？ 如果是这个问题，那么已经修复了（如果不是请告诉我们什么问题）。 在这个提交修复了 https://github.com/linuxdeepin/qt5integration/commit/1a54067cf61ec96206cda39ee59995b232f9a53a

**Comment by chen244** [comment]
> 1. 最大最小化这些按钮和windowFlags相关，setfixedsize只是禁止， 可以通过setWindowFlags的方法隐藏，如下
>    `setWindowFlags(windowFlags() & ~(Qt::WindowMinimizeButtonHint |  Qt::WindowMaximizeButtonHint |  Qt::WindowCloseButtonHint));`
> 2. 这个样式阔以通过命令行参数禁用，如`VirtualBox --style fusion` 这样应该阔以解决你的烦恼。。
> 3. 万年的spinbox问题是否指的是spinbox中的edit太窄了？ 如果是这个问题，那么已经修复了（如果不是请告诉我们什么问题）。 在这个提交修复了 [linuxdeepin/qt5integration@1a54067](https://github.com/linuxdeepin/qt5integration/commit/1a54067cf61ec96206cda39ee59995b232f9a53a)

![截图_选择区域_20210415101921](https://user-images.githubusercontent.com/60290287/114804574-16700600-9dd4-11eb-8ebb-0763c1c2bd2f.png)
宽度还是太窄，在输入最大数字时候spinbox依然有遮挡，多增加一两毫米

**Comment by BLumia** [comment]
现在应该好很多了，可以更新下试试看。如果更新后仍有问题，可在 [developer-center](https://github.com/linuxdeepin/developer-center/) 开新的 issue 进行反馈，我们会在新的 issue 里跟进问题。

感谢支持！
