### ISSUE TITLE
能不能出一个python版本的,毕竟现在很多人使用PyQt5开发应用

### ISSUE THREAD

**Issue by jinxiangwzh** [linuxdeepin/dtkwidget#73]

**Comment by BLumia** [comment]
抱歉现在才予以答复，我们之前很少留意 developer-center 之外的反馈。

暂时恐怕不会提供官方的 python binding，不过社区有意向的话可以尝试搞一搞然后分享给社区 :)

如果有其它的问题的话，可在 [developer-center](https://github.com/linuxdeepin/developer-center/) 与我们联系，感谢支持！
