### ISSUE TITLE
你们对这个样式的处理是直接换成button啊

### ISSUE THREAD

**Issue by chen244** [linuxdeepin/dtkwidget#74]
![截图_选择区域_20210426163357](https://user-images.githubusercontent.com/60290287/116055249-14992300-a6af-11eb-8bd4-8774999de8a0.png)
这个地方换成button啊
![截图_选择区域_20210426164806](https://user-images.githubusercontent.com/60290287/116055365-34c8e200-a6af-11eb-8f94-7394bde3b537.png)
离谱

**Comment by kegechen** [comment]
不是换成button，只是风格是这样， 如果想要矩形可以试试
 DTabBar::setEnabledEmbedStyle 启用直角样式的Tabbar
