### ISSUE TITLE
5.4.20 doesn't build for Qt 5.15~6.1

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dtkwidget#76]
![2021-05-17-234453-0ac0aa](https://user-images.githubusercontent.com/1006477/118523055-588fbd00-b76f-11eb-98b7-7e4ab97f4f95.png)

But the enum is actually added since 6.2, according to official Qt documentation:
![2021-05-17-234421-e16d2b](https://user-images.githubusercontent.com/1006477/118523112-66ddd900-b76f-11eb-8a99-265a93675919.png)

So it doesn't build on, for example, Qt 5.15:
![2021-05-17-234441-f31f6d](https://user-images.githubusercontent.com/1006477/118523148-70ffd780-b76f-11eb-842b-e3d7f504f1c4.png)

**Comment by BLumia** [comment]
这个问题应该已经不再存在了，先 close 了
