### ISSUE TITLE
DDialog 中添加 DLineEdit 控件，DLineEdit 右侧的取消图标模糊 

### ISSUE THREAD

**Issue by jiangzc** [linuxdeepin/dtkwidget#77]
DDialog 中添加 DLineEdit 控件，DLineEdit 右侧的取消图标模糊 

鼠标点击下图，DDialog 中的DLineEdit 右侧的取消图标模糊 
![image](https://user-images.githubusercontent.com/13901512/120433100-69fed900-c3ad-11eb-9c3a-33394abfdf40.png)

版本： deepin v20.2.1

测试代码
```cpp
        DDialog dd(this);
        dd.setTitle("快速添加新的任务");
        DLineEdit *lineEdit = new DLineEdit;
        lineEdit->setFixedWidth(250);
        dd.addSpacing(30);
        dd.addContent(lineEdit, Qt::AlignCenter);
        dd.addSpacing(20);
        dd.addButton("确定", true);
        dd.addButton("取消", false);
        lineEdit->setFocus();
        qInfo() << dd.exec();
```

**Comment by BLumia** [comment]
抱歉现在才予以答复，我们之前很少留意 developer-center 之外的反馈。

v20.5 所附的 DTK 应该不再有这个问题了，可以更新下试试看。如果更新后仍有问题，可在 [developer-center](https://github.com/linuxdeepin/developer-center/) 开新的 issue 进行反馈，我们会在新的 issue 里跟进问题。

感谢支持！
