### ISSUE TITLE
中文环境搜索框placeholder显示“Search”

### ISSUE THREAD

**Issue by zoze0** [linuxdeepin/dtkwidget#78]
## 缺陷描述

中文环境搜索框placeholder显示“Search”
## 复现步骤

开始菜单，商店，设置中心搜索框皆可复现
## 期望行为

显示对应语言的placeholder，如“搜索”
## 截图

![0003](https://user-images.githubusercontent.com/20562449/90309051-5ca85900-df17-11ea-9f5d-c158921fdecd.png)

### 发行版以及版本

deepin20 （已更新最新版）

**Comment by BLumia** [comment]
v20.5 不再有此问题，如果以后仍然遇到此问题的话欢迎在 developer-center 开新的 issue 进行反馈，感谢！
