### ISSUE TITLE
无法安装libdframeworkdbus-dev

### ISSUE THREAD

**Issue by YancyPeng** [linuxdeepin/dtkwidget#8]
不管如何更新源，都无法安装

**Comment by YancyPeng** [comment]
dpkg-buildpackage: 源码包 dtkwidget
dpkg-buildpackage: 源码版本 2.0.0-0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: 源码修改者 Iceyer <me@iceyer.net>
dpkg-buildpackage: 主机架构 amd64
 dpkg-source --before-build dtkwidget-master
dpkg-checkbuilddeps: 错误: Unmet build dependencies: libdframeworkdbus-dev
dpkg-buildpackage: 警告: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: 警告: (使用 -d 参数来忽略)

**Comment by YancyPeng** [comment]
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 libdframeworkdbus-dev

**Comment by Iceyer** [comment]
是用的deepin的仓库吗，这个包在deepin仓库是可以直接安装的

```
apt-cache policy  libdframeworkdbus-dev
libdframeworkdbus-dev:
  版本列表：
     0.4.2-1 500
        500 http://pools.corp.deepin.com/deepin panda/main amd64 Packages

```
如该不是Deepin仓库，先编译这个包：
https://github.com/linuxdeepin/dde-qt-dbus-factory
