### ISSUE TITLE
全局菜单支持

### ISSUE THREAD

**Issue by SeptemberHX** [linuxdeepin/dtkwidget#85]
目前所有 dtk 的程序使用的 DTitleBar 中的菜单均没有支持基于 `com.canonical.AppMenu.Registrar.xml` 以及 `com.canonical.dbusmenu.xml` 的全局菜单。然而 Qt 原版是支持的。希望能够将该功能添加回来。

![image](https://user-images.githubusercontent.com/18042424/125182119-dcc96280-e23d-11eb-87ab-782a974638b4.png)

**Comment by BLumia** [comment]
抱歉现在才予以答复。建议用 Qt 的来支持全局菜单。DTK 应用设计上是没全局菜单这个概念的，所以恐怕暂时不会做这个支持 = =

如果您对此有别的想法或者希望发起讨论，可以在 [developer-center](https://github.com/linuxdeepin/developer-center/) 仓库的 discussion 板块与我们讨论，这个 issue 就先关闭了。
